name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  example_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "COMMAND 0 EXECUTED"
      - run: echo "COMMAND 1 EXECUTED"